workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.example.year4Project
      vars:
        FL_INCREMENTOR: 1
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
        - pattern: 'develop'
          include: true
    scripts:
      - name: Set up Flutter
        script: |
          flutter clean
          flutter pub get
          flutter pub upgrade

      - name: Increment build number
        script: |
          # Generate a unique build number
          BUILD_NUMBER=$(($(date +%y%m%d%H%M) + 100))
          sed -i '' "s/version: .*+[0-9]*/version: 1.0.1+$BUILD_NUMBER/" pubspec.yaml

      - name: Build iOS
        script: |
          flutter build ios --release
          cd ios
          pod install
          xcodebuild clean archive \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/Runner.xcarchive \
            CODE_SIGNING_ALLOWED=NO

      - name: Create IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportOptionsPlist /Users/builder/export_options.plist \
            -exportPath build/ios/ipa

    artifacts:
      - build/ios/ipa/*.ipa
      - build/Runner.xcarchive

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY    # Set this in Codemagic environment variables
        key_id: $APP_STORE_CONNECT_KEY_ID      # Set this in Codemagic environment variables
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID # Set this in Codemagic environment variables
        submit_to_testflight: true
        beta_groups:                           # Optional: specify TestFlight groups
          - "External Testers"

  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    environment:
      android_signing:
        - keystore_reference
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
        - pattern: 'develop'
          include: true
    scripts:
      - name: Set up Flutter
        script: |
          flutter clean
          flutter pub get
          flutter pub upgrade

      - name: Build APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/*.apk